---
title: "Plots and Figures"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
Names <-rep(c("Dara", "Azalea", "Barbi", "Rowena", "Fiona"),each=2)
MF <- rnorm(10,45,25) # 10 is the number of numbers you want, and 45 to 25 is the range
Condition <- rep(c("Social","NonSocial"),5)
Aversity <- rep(c("A","N_A" ),times=c(4,6))
  plot_df <- data.frame(Names, MF, Condition, Aversity)
  
  ggplot(plot_df, aes(x=Condition, y=MF, group=Names, linetype=Aversity))+
    geom_line()+
    geom_text(label=Names)+
    theme_classic()


```



```{r}
library(ggplot2)
 nonsocial_risk <- c(45,12,4,28,33,58,60)
  social_risk <- c(20,20,4,50,48,52,60)
  figure_df <- data.frame(nonsocial_risk,social_risk)
  
  ggplot(figure_df, aes(x=nonsocial_risk,y=social_risk)) + 
    geom_point(size=3) + 
    geom_smooth(method="lm", se = FALSE) +
    theme_classic() +
    xlab("Avarage Frequency of Non Social Risk") +
    ylab("Avarage Frequency of Social Risk") +
    scale_y_continuous(breaks = seq(0, 100, by = 10)) +
    scale_x_continuous(breaks = seq(0, 100, by = 10))


```

```{r}
library(ggplot2)
  study_group <- c(doctor_study = rep("Doctor Study", 6), butcher_study = rep("Butcher Study", 6), 
             firefighter_study = rep("Firefighter Study", 6), 
             construction_worker_study = rep("Construction Worker Study", 6))
  eval_data <- c(2,3,4,2,3,6,5,4,3,4,4,2,2,7,7,6,6,8,6,6,5,6,7,8)
  figure_df2 <- data.frame(study_group,eval_data)
  
  ggplot(figure_df2, aes(factor(study_group), eval_data)) +
    geom_violin(fill="gray70") +
    theme_classic() +
    ylab("Person X evaluations") +
    xlab("")
  
```

```{r}
library(ggplot2)
  study_group <- rep(as.factor(c("Doctor Study", "Butcher Study", "firefighter_study", "Construction Worker Study")),3)
  occurance <- rep(as.factor(c("women more likely", "equilly likely","man more likely")),4)
  dv_means <- c(20,30,40,40)
dv_SEs   <- c(4,3.4,3)
plot_df3 <- data.frame(study_group,
                      occurance,
                      dv_means,
                      dv_SEs)
  
  ggplot(plot_df3, aes(x=study_group,y=dv_means, # aestetics definition has gotten 
                    group=occurance, 
                   # color=factor_two))+  # color here means the border collor
                    fill=occurance))+
  geom_bar(stat="identity", 
           position="dodge",
           color="black")
  
```

```{r}
factor_one <- rep(as.factor(c("A","B","C")),2) # this 2 means repeat ABC twice
factor_two <- rep(as.factor(c("IIA","IIB")),3)
dv_means <- c(20,30,40,20,40,40)
dv_SEs   <- c(4,3.4,4,3,2,4)
plot_df <- data.frame(factor_one,
                      factor_two,
                      dv_means,
                      dv_SEs)

# basic bar graph

ggplot(plot_df, aes(x=factor_one,y=dv_means, # aestetics definition has gotten 
                    group=factor_two, 
                   # color=factor_two))+  # color here means the border collor
                    fill=factor_two))+
  geom_bar(stat="identity", 
           position="dodge",
           color="black")
```



