---
title: "Statistics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Creating two samples that come from a normal distribution 
```{r}
distribution <- c()

    for(i in 1:10000) {
    vector_1 <- rnorm(10,0,1)
    vector_2 <- rnorm(10,0,1)
    distribution <- c(distribution,mean(vector_2)-mean(vector_1))
    }
    y <- hist(distribution)
```


```{r}
plot(density(distribution))
```






```{r}
a <- replicate(10000,t.test(rnorm(10,0,1),rnorm(10,0,1))$p.value)
hist(a)
```


```{r}
a <- replicate(10000,t.test(rnorm(10,0,1),rnorm(10,0,1))$statistic)
hist(a)
```

```{r}
t <- .5
df <- 9
(1 - pt(q = abs(t), df = df))*2
```

```{r}
t <- 1
df <- 9
(1 - pt(q = abs(t), df = df))*2
```

```{r}
t <- 1.5
df <- 9
(1 - pt(q = abs(t), df = df))*2
```

```{r}
t <- 2
df <- 9
(1 - pt(q = abs(t), df = df))*2
```

```{r}
t <- 2.5
df <- 9
(1 - pt(q = abs(t), df = df))*2
```


```{r}
testScores <- rnorm(10, mean = 0, sd = 1)
t.test(testScores,mu=0)
t_dist <-runif(10000)

```

# T null distribution
```{r}
 T_distribution <- c()

    for(i in 1:10000) {
      vector_3 <- rnorm(10,0,1)
      T_distribution <- c(T_distribution,(mean(vector_3)- 0)/(sd(vector_3)/(sqrt(length(vector_3)))))
    }
    hist(T_distribution)

```


# correlation

```{r}
x <- rnorm(10,0,1)
y <- rnorm(10,0,1)
cor(x,y)

```
```{r}
correlation_dist <- c()

    for(i in 1:10000) {
    vector_1 <- rnorm(10,0,1)
    vector_2 <- rnorm(10,0,1)
    correlation_dist <- c(correlation_dist, cor(vector_1,vector_2))
    }

    hist(correlation_dist)
```

### Critical value

```{r}
zd <- density(correlation_dist)

    c_1 <- which(zd$y >= 0.05)
    abs(zd$x[c_1[1]])
```


# F Values ANOVA

```{r,eval=F}
A <- c(1,2,3,4)
B <- c(3,4,5,6)
C <- c(5,6,7,8)
Subjects <- rep(1:10,each=4)
Factor1 <- rep(rep(c("A","B","C"), each = 4), 10)
Factor2 <- rep(rep(c("1","2"), 2), 10)
meanvalue_subject <- c(A,B,C)

all_data <- data.frame(Subjects = as.factor(Subjects),
                       DV,
                       Factor1,
                       Factor2)
    aov_output <- aov(meanvalue_subject~A*B*C, all_data)

library(xtable)

```

```{r, eval=F}
    knitr::kable(xtable(summary(aov_output)))

```


















